title: "Wilson W. Wandu"
description: "Tech Strategist | BI & Automation Innovator | Storytelling That Drives Action"
avatar: "/assets/Wilson-Passport.png"
</p>
title: "Wilson W Wandu"
description: "My Portfolio"
description: "💡 BI Developer | Instructional Designer | IT Strategist"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
