</p>
title: "Wilson W. Wandu"
avatar: "/assets/Wilson-Passport.png"
description: "My Portfolio"
description: "💡 Tech Strategist | BI & Automation Innovator | Storytelling That Drives Action"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
