<p align="center">
  <img src="https://raw.githubusercontent.com/WWWandu/Wandu.github.io/main/assets/Wilson%20Passport.png"
       alt="Wilson W. Wandu"
       width="180"
       style="border-radius: 50%; object-fit: cover; box-shadow: 0 0 15px rgba(123, 97, 255, 0.5);" />
</p>
title: "Wilson W Wandu"
description: "My Portfolio"
description: "💡 BI Developer | Instructional Designer | IT Strategist"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
