<!-- Profile Photo at the Top -->
<div style="text-align: center; margin-top: 30px;">
  <img src="assets/Wilson-Passport.png"
       alt="Wilson W. Wandu"
       width="180"
       style="border-radius: 50%; object-fit: cover; box-shadow: 0 0 20px rgba(106, 90, 205, 0.5);" />
  <h1 style="margin-top: 15px;">Wilson W. Wandu</h1>
  <p>Tech Strategist | BI & Automation Innovator | Storytelling That Drives Action</p>
</div>
</p>
title: "Wilson W Wandu"
description: "My Portfolio"
description: "💡 BI Developer | Instructional Designer | IT Strategist"
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
